/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        // Canonical: Fredoka (UI) + Space Mono (meta/amounts)
        retro: ["Fredoka_500Medium", "Fredoka", "sans-serif"],
        "retro-bold": ["Fredoka_700Bold", "Fredoka", "sans-serif"],
        "retro-mono": [
          "SpaceMono_400Regular",
          "Space Mono",
          "SF Mono",
          "Consolas",
          "monospace",
        ],
        "retro-mono-bold": [
          "SpaceMono_700Bold",
          "Space Mono",
          "SF Mono",
          "Consolas",
          "monospace",
        ],
        // Legacy aliases → same faces (no Inter)
        sans: ["Fredoka_500Medium", "Fredoka", "sans-serif"],
        "sans-medium": ["Fredoka_700Bold", "Fredoka", "sans-serif"],
        display: ["Fredoka_500Medium", "Fredoka", "sans-serif"],
        "display-medium": ["Fredoka_700Bold", "Fredoka", "sans-serif"],
        mono: [
          "SpaceMono_400Regular",
          "Space Mono",
          "SF Mono",
          "Consolas",
          "monospace",
        ],
        "mono-medium": [
          "SpaceMono_700Bold",
          "Space Mono",
          "SF Mono",
          "Consolas",
          "monospace",
        ],
      },
      colors: {
        "dono-primary": "#159E88",
        "dono-primary-dark": "#0F7A6A",
        "dono-accent": "#F8B400",
        "dono-accent-dark": "#D49A00",
        "dono-cyan": "#211E1A",
        "dono-green": "#159E88",
        "dono-amber": "#F8B400",
        "dono-bg": "#FBEEDD",
        "dono-cream": "#FBEEDD",
        "dono-surface": "#FFF9EF",
        "dono-surface-muted": "#F1E7D6",
        "dono-text": "#211E1A",
        "dono-muted": "#5c574f",
        "dono-border": "#211E1A",
        "retro-cream": "#FBEEDD",
        "retro-paper": "#FFF9EF",
        "retro-ink": "#211E1A",
        "retro-coral": "#F2542D",
        "retro-marigold": "#F8B400",
        "retro-sky": "#2E97D6",
        "retro-mint": "#159E88",
        "retro-pink": "#F17FB3",
        "retro-indigo": "#4D5FE3",
        "retro-tan": "#B98A4E",
      },
    },
  },
  plugins: [],
};
