/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter_400Regular", "Inter", "-apple-system", "sans-serif"],
        "sans-medium": ["Inter_500Medium", "Inter", "-apple-system", "sans-serif"],
        display: ["Fraunces_400Regular", "Fraunces", "Georgia", "serif"],
        "display-medium": [
          "Fraunces_500Medium",
          "Fraunces",
          "Georgia",
          "serif",
        ],
        mono: [
          "JetBrainsMono_400Regular",
          "JetBrains Mono",
          "SF Mono",
          "Consolas",
          "monospace",
        ],
        "mono-medium": [
          "JetBrainsMono_500Medium",
          "JetBrains Mono",
          "SF Mono",
          "Consolas",
          "monospace",
        ],
        retro: ["Fredoka_500Medium", "Fredoka", "sans-serif"],
        "retro-bold": ["Fredoka_700Bold", "Fredoka", "sans-serif"],
        "retro-mono": [
          "SpaceMono_400Regular",
          "Space Mono",
          "SF Mono",
          "Consolas",
          "monospace",
        ],
        "retro-mono-bold": [
          "SpaceMono_700Bold",
          "Space Mono",
          "SF Mono",
          "Consolas",
          "monospace",
        ],
      },
      colors: {
        "dono-primary": "#2f6844",
        "dono-primary-dark": "#245538",
        "dono-accent": "#6BAF92",
        "dono-accent-dark": "#245538",
        "dono-cyan": "#1c2420",
        "dono-green": "#2f6844",
        "dono-amber": "#1c2420",
        "dono-bg": "#f4f7f3",
        "dono-cream": "#f4f7f3",
        "dono-surface": "#ffffff",
        "dono-surface-muted": "#eaf1ea",
        "dono-text": "#1c2420",
        "dono-muted": "#56615A",
        "dono-border": "#e8e3da",
        "retro-cream": "#FBEEDD",
        "retro-paper": "#FFF9EF",
        "retro-ink": "#211E1A",
        "retro-coral": "#F2542D",
        "retro-marigold": "#F8B400",
        "retro-sky": "#2E97D6",
        "retro-mint": "#159E88",
        "retro-pink": "#F17FB3",
        "retro-indigo": "#4D5FE3",
        "retro-tan": "#B98A4E",
      },
    },
  },
  plugins: [],
};
